# Generated by Django 3.2.12 on 2022-10-31 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_cost', models.IntegerField()),
                ('per_week', models.IntegerField()),
                ('lesson_duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='images/480x270.png', upload_to='course-img/')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('main_info', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pricing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.pricing')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
