# Generated by Django 3.2.12 on 2022-10-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bio',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
