# Generated by Django 3.2.12 on 2022-10-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bio',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
